// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvbG--ogg0CHXQ7kc-iz4XLeAJU0cV6Wo',
    appId: '1:229523797852:android:1e0f10dd3f3ee187cb3399',
    messagingSenderId: '229523797852',
    projectId: 'draftproject-acd7e',
    authDomain: 'draftproject-8a474.firebaseapp.com',
    storageBucket: 'draftproject-acd7e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvbG--ogg0CHXQ7kc-iz4XLeAJU0cV6Wo',
    appId: '1:229523797852:android:1e0f10dd3f3ee187cb3399',
    messagingSenderId: '229523797852',
    projectId: 'draftproject-acd7e',
    storageBucket: 'draftproject-acd7e.firebasestorage.app',
  );
}
