// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf4hxuqKZGdj9M5LcjBtcgGat2ljphxLI',
    appId: '1:172684762906:web:fac0d6c18c26d3387f56a3',
    messagingSenderId: '172684762906',
    projectId: 'draftproject-8a474',
    authDomain: 'draftproject-8a474.firebaseapp.com',
    storageBucket: 'draftproject-8a474.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHxAdF1pc8KevOc4jniqi60zx1q_rJgxc',
    appId: '1:172684762906:android:f06fc32f3215fc217f56a3',
    messagingSenderId: '172684762906',
    projectId: 'draftproject-8a474',
    storageBucket: 'draftproject-8a474.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLjGBv6qhXTvHs0eLCCMbVrKxiryCdAo0',
    appId: '1:172684762906:ios:8c895bbf42c6bc1e7f56a3',
    messagingSenderId: '172684762906',
    projectId: 'draftproject-8a474',
    storageBucket: 'draftproject-8a474.firebasestorage.app',
    iosBundleId: 'com.example.draftproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLjGBv6qhXTvHs0eLCCMbVrKxiryCdAo0',
    appId: '1:172684762906:ios:8c895bbf42c6bc1e7f56a3',
    messagingSenderId: '172684762906',
    projectId: 'draftproject-8a474',
    storageBucket: 'draftproject-8a474.firebasestorage.app',
    iosBundleId: 'com.example.draftproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf4hxuqKZGdj9M5LcjBtcgGat2ljphxLI',
    appId: '1:172684762906:web:c0dfcb6e4687c3b17f56a3',
    messagingSenderId: '172684762906',
    projectId: 'draftproject-8a474',
    authDomain: 'draftproject-8a474.firebaseapp.com',
    storageBucket: 'draftproject-8a474.firebasestorage.app',
  );
}
